# Carbon Dioxide Emissions Data

In [32]:
import pandas as pd

In [33]:
df = pd.read_csv('carbon_dioxide_emissions.csv')

In [34]:
# Create df copy
co2_df = df.copy()
co2_df.head()

,Series Name,Series Code,Country Name,Country Code,2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
0,Carbon dioxide (CO2) net fluxes from LULUCF - ...,EN.GHG.CO2.LU.DF.MT.CE.AR5,Cambodia,KHM,43.7080,32.6168,32.6168,32.6168,32.6168,32.6168,32.6168,32.6168,0.0,0
1,Carbon dioxide (CO2) net fluxes from LULUCF - ...,EN.GHG.CO2.LU.DF.MT.CE.AR5,Indonesia,IDN,245.5048,198.4763,167.3184,180.3968,48.0863,57.1721,45.7679,45.7679,0.0,0
2,Carbon dioxide (CO2) net fluxes from LULUCF - ...,EN.GHG.CO2.LU.DF.MT.CE.AR5,Philippines,PHL,15.4495,25.9306,51.5264,51.5264,51.5264,51.5264,51.5264,51.5264,0.0,0
3,Carbon dioxide (CO2) net fluxes from LULUCF - ...,EN.GHG.CO2.LU.DF.MT.CE.AR5,Viet Nam,VNM,13.5448,13.5448,13.5448,13.5448,13.5448,13.5448,13.5448,13.5448,0.0,0
4,Carbon dioxide (CO2) net fluxes from LULUCF - ...,EN.GHG.CO2.LU.DF.MT.CE.AR5,Myanmar,MMR,53.8075,53.8075,53.8075,53.8075,53.8075,53.8075,53.8075,53.8075,0.0,0

In [35]:
# Remove unnecessary columns
co2_df.drop(columns=['Series Code', 'Country Code'], inplace=True)
co2_df.head()

,Series Name,Country Name,2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
0,Carbon dioxide (CO2) net fluxes from LULUCF - ...,Cambodia,43.7080,32.6168,32.6168,32.6168,32.6168,32.6168,32.6168,32.6168,0.0,0
1,Carbon dioxide (CO2) net fluxes from LULUCF - ...,Indonesia,245.5048,198.4763,167.3184,180.3968,48.0863,57.1721,45.7679,45.7679,0.0,0
2,Carbon dioxide (CO2) net fluxes from LULUCF - ...,Philippines,15.4495,25.9306,51.5264,51.5264,51.5264,51.5264,51.5264,51.5264,0.0,0
3,Carbon dioxide (CO2) net fluxes from LULUCF - ...,Viet Nam,13.5448,13.5448,13.5448,13.5448,13.5448,13.5448,13.5448,13.5448,0.0,0
4,Carbon dioxide (CO2) net fluxes from LULUCF - ...,Myanmar,53.8075,53.8075,53.8075,53.8075,53.8075,53.8075,53.8075,53.8075,0.0,0

In [36]:
# Remove bracketed year tags from year columns (e.g., '2016 [YR2016]' -> '2016')
co2_df.columns = co2_df.columns.str.replace(r'\s*\[YR\d{4}\]', '', regex=True)

In [37]:
# Rename Series Names to shorter names
series_name_dict = {
    'Carbon dioxide (CO2) net fluxes from LULUCF - Deforestation (Mt CO2e)': 'Deforestation CO2 Emissions (tonnes)',
    'Carbon dioxide (CO2) emissions from Industrial Processes (Mt CO2e)': 'Industrial CO2 Emissions (tonnes)',
    'Carbon dioxide (CO2) emissions from Building (Energy) (Mt CO2e)': 'Building Energy CO2 Emissions (tonnes)',
}
co2_df['Series Name'] = co2_df['Series Name'].map(series_name_dict)

In [38]:
# Change df to long format
year_cols = [col for col in co2_df.columns if str(col).isdigit()]

co2_long_df = co2_df.melt(
    id_vars=['Series Name', 'Country Name'],
    value_vars=year_cols,
    var_name='Year',
    value_name='CO2 Value'
)

co2_long_df['Year'] = co2_long_df['Year'].astype(int)
co2_long_df['CO2 Value'] = pd.to_numeric(co2_long_df['CO2 Value'], errors='coerce')
co2_long_df = co2_long_df.dropna(subset=['CO2 Value'])
co2_long_df = co2_long_df.sort_values(['Country Name', 'Series Name', 'Year']).reset_index(drop=True)

In [43]:
# Normal format
co2_df.head()

,Series Name,Country Name,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Deforestation CO2 Emissions (tonnes),Cambodia,43.7080,32.6168,32.6168,32.6168,32.6168,32.6168,32.6168,32.6168,0.0,0
1,Deforestation CO2 Emissions (tonnes),Indonesia,245.5048,198.4763,167.3184,180.3968,48.0863,57.1721,45.7679,45.7679,0.0,0
2,Deforestation CO2 Emissions (tonnes),Philippines,15.4495,25.9306,51.5264,51.5264,51.5264,51.5264,51.5264,51.5264,0.0,0
3,Deforestation CO2 Emissions (tonnes),Viet Nam,13.5448,13.5448,13.5448,13.5448,13.5448,13.5448,13.5448,13.5448,0.0,0
4,Deforestation CO2 Emissions (tonnes),Myanmar,53.8075,53.8075,53.8075,53.8075,53.8075,53.8075,53.8075,53.8075,0.0,0

In [44]:
# Long format df
co2_long_df.head()

                              Series Name Country Name  Year  CO2 Value
0  Building Energy CO2 Emissions (tonnes)     Cambodia  2016     1.0391
1  Building Energy CO2 Emissions (tonnes)     Cambodia  2017     1.1064
2  Building Energy CO2 Emissions (tonnes)     Cambodia  2018     0.9218
3  Building Energy CO2 Emissions (tonnes)     Cambodia  2019     1.1568
4  Building Energy CO2 Emissions (tonnes)     Cambodia  2020     1.4201

In [45]:
# Save normal format as CSV
co2_df.to_csv('co2_emissions_clean.csv', index=False)

In [46]:
# Save long format as CSV
co2_long_df.to_csv('co2_emissions_long_clean.csv', index=False)